import Head from "next/head";
import React from "react";
import ErrorPagesSection1 from "../containers/ErrorPages/ErrorPages-Section1/ErrorPages-Section1";
import FooterBigSight from "../containers/Footer/Footer";
import "bootstrap/dist/css/bootstrap.min.css";

export default function NotFound() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={"Footer-Container"}>
                <FooterBigSight />
            </div>
            <ErrorPagesSection1 />
        </div>
    );
}
